apiVersion : apps/v1
kind: Deployment
metadata:
  name: anonymousnodejsapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anonymousnodejsapp
  template:
    metadata:
      labels:
        app: anonymousnodejsapp 
    spec:
      containers:
        - name: anonymousnodejsapp 
          image: testreg2123.azurecr.io/anonymousnodejsapp
          ports:
          - containerPort: 3600